name: hrmanager
channels:
  - conda-forge
  - defaults
dependencies:
  - autopep8
  - flake8
  - jupyter
  - lightgbm
  - matplotlib
  - pandas
  - pre-commit
  - python=3.8.6
  - rope
  - scikit-learn
  - xgboost
